// <auto-generated />
namespace Auction_Prop_Buyers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class t : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101504312_t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
